# Generated by Django 4.2.7 on 2023-11-12 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_products_order_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stok_level',
            new_name='stock_level',
        ),
    ]
